### ISSUE TITLE
Errors with Event add Method

### ISSUE THREAD

**Issue by tobias-github** [Pet-Platoon/types-ragemp-client#1]
ERROR in ./src/main/system/event/Game/VehicleDeathEvent.ts
(9,39): error TS2345: Argument of type '(vehicle: MpVehicle, reason: string, killer: MpPlayer) => void' is not assignable to parameter of type '(player: MpPlayer, ...args: any[]) => void'.
  Types of parameters 'vehicle' and 'player' are incompatible.
    Type 'MpPlayer' is not assignable to type 'MpVehicle'.
      Property 'gear' is missing in type 'MpPlayer'.

ERROR in ./src/main/system/event/Game/PlayerRuleTriggeredEvent.ts
(8,46): error TS2345: Argument of type '(rule: string, counter: number) => void' is not assignable to parameter of type '(player: MpPlayer, ...args: any[]) => void'.
  Types of parameters 'rule' and 'player' are incompatible.
    Type 'MpPlayer' is not assignable to type 'string'.

ERROR in ./src/main/system/event/Game/PlayerQuitEvent.ts
(8,37): error TS2345: Argument of type '(exitType: string, reason: string) => void' is not assignable to parameter of type '(player: MpPlayer, ...args: any[]) => void'.
  Types of parameters 'exitType' and 'player' are incompatible.
    Type 'MpPlayer' is not assignable to type 'string'.

ERROR in ./src/main/system/event/Game/PlayerDeathEvent.ts
(8,38): error TS2345: Argument of type '(reason: string, killer: MpPlayer) => void' is not assignable to parameter of type '(player: MpPlayer, ...args: any[]) => void'.
  Types of parameters 'reason' and 'player' are incompatible.
    Type 'MpPlayer' is not assignable to type 'string'.

ERROR in ./src/main/system/event/Game/PlayerCommandEvent.ts
(8,40): error TS2345: Argument of type '(command: string) => void' is not assignable to parameter of type '(player: MpPlayer, ...args: any[]) => void'.
  Types of parameters 'command' and 'player' are incompatible.
    Type 'MpPlayer' is not assignable to type 'string'.

ERROR in ./src/main/system/event/Game/PlayerChatEvent.ts
(8,37): error TS2345: Argument of type '(text: string) => void' is not assignable to parameter of type '(player: MpPlayer, ...args: any[]) => void'.
  Types of parameters 'text' and 'player' are incompatible.
    Type 'MpPlayer' is not assignable to type 'string'.

**Comment by nick-strohm** [comment]
Possible fix in https://github.com/Pet-Platoon/types-ragemp-client/commit/f948fd080ade56916305be007fc5acd8889222f7. Needs QA

**Comment by nick-strohm** [comment]
Reviewed by @tobias-github. Merged into master
